site_name: Arro mods
site_url: https://arro-mods.cc
theme:
  name: material
  custom_dir: assets
  font:
    text: Ubuntu
    code: JetBrains Mono
  favicon: images/logo/arro_profile.png
  logo: images/logo/arro_profile.png
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    # - navigation.sections
    # - navigation.expand
    - navigation.path
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: green

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: green
extra_css:
  - stylesheets/header.css
  - stylesheets/tabs.css
  - stylesheets/footer.css
  - stylesheets/effects.css
  - stylesheets/codeblocks.css
  - stylesheets/extra.css
  - stylesheets/drawer.css
extra:
  generator: false
extra_javascript:
  - javascripts/logo-hover.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  
watch:
  - assets

nav:
  - Home: index.md
  - Mods:
      - Mods/index.md
      - Test: Mods/test.md
  - Guides:
      - Guides/index.md
      - Test: Guides/test.md
  - Common:
      - Common/index.md
      - Test: Common/test.md
  - Tools:
      - Tools/index.md
      - RECTF: 
          - Tools/RECTF/index.md     #CLICKABLE
          - Usage: Tools/RECTF/usage.md      # FIRST
          - Examples: Tools/RECTF/examples.md   # SECOND etc.
      - ImagShow: 
          - Tools/ImagShow/index.md